"""updated user_type enum

Revision ID: dfbf40c8fdcd
Revises: 2a1d48bdc711
Create Date: 2026-03-31 00:32:22.750223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbf40c8fdcd'
down_revision = '2a1d48bdc711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Member', 'Admin', name='user_types'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.Enum('Member', 'Admin', name='user_types'),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
