"""added employee, trainer and salary model

Revision ID: ea46e5df0895
Revises: dfbf40c8fdcd
Create Date: 2026-04-01 23:23:47.777140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea46e5df0895'
down_revision = 'dfbf40c8fdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender_types'), nullable=False),
    sa.Column('employee_type', sa.Enum('Manager', 'Trainer', 'Receptionist', 'Helper', 'Cleaner', name='employee_types'), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('credited', sa.Boolean(), nullable=True),
    sa.Column('credited_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('speciality', sa.String(length=255), nullable=False),
    sa.Column('trainer_type', sa.Enum('General Trainer', 'Personal Trainer', name='trainer_types'), nullable=False),
    sa.Column('pt_monthly_fee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainers')
    op.drop_table('salaries')
    op.drop_table('employees')
    # ### end Alembic commands ###
