"""removed payment method

Revision ID: f771bf3d4fd5
Revises: c13f5915f2c3
Create Date: 2026-04-09 22:49:41.980901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f771bf3d4fd5'
down_revision = 'c13f5915f2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
